### ISSUE TITLE
Schedule doesn’t show up

### ISSUE THREAD

**Issue by PlogmannC** [Cin316/X-Schedule#8] opened 2017-10-04 23:03 UTC
Every time I open the app it says no classes. The schedule just doesn’t show up.

**Comment by Cin316** [comment] 2017-10-05 18:31
This is a new known problem with the app.  I've gotten multiple reports.  I've been talking to Mr. Brass, who manages the St. X website.  What seems to be happening is that FinalSite (the website provider for St. X) is throttling requests to the app because there are so many.  If I make some changes to the code, I should be able to reduce the load on the St. X website and fix the problem.  I've just got to get the time to fix it in my busy schedule.  Thanks for the feedback!

This is the same problem as issue #6.

Closed as a duplicate of #6.

**Closed as completed by Cin316** 2017-10-05 18:31 UTC
